{LOAD bfpp.bfh}
{D NEWLINE {x10{INCR}}}
{D ASTERISK {x42{INCR}}}
{D REMOVE TONULL}


REMOVE VALUE FROM CELL THEN
ADD NEWLINE VALUE TO CELL THEN
PUSH CURRENT VALUE TO STACK THEN
WE NEED TO REMOVE NEWLINE SO LETS REMOVE IT
ADD ASTERISK VALUE TO CELL THEN
PUSH CURRENT VALUE TO STACK THEN
REMOVE IT AGAIN THEN
POP CURRENT VALUE FROM STACK AND PRINT IT AND REMOVE THE VALUE
AGAIN: POP CURRENT VALUE FROM STACK AND PRINT IT AND REMOVE THE VALUE
